[package]
name = "pbr-cli"
version = "0.1.0"
authors = ["bretzle <johnfish218@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbr-core = { path = "../pbr-core" }
maths = { path = "../maths" }